### ISSUE TITLE
add full customizepkg support

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#12]
Implement custumizepkg support. Issue #8 must be solved to allow full support.

**Comment by CyberShadow** [comment]
> user wants to remove deps + add --disable-xxx build-options to avoid unwanted functionality

Sometimes there are situations where it is desired to *enable* functionality that is otherwise not enabled by default or Arch's PKGBUILD. This can be the case of experimental features. Concrete example: Emacs 25 widget embedding and native-code interop.

Another use case is to enable features that are otherwise incompatible with the default ones. Concrete example: Emacs' widget toolkit, in order to avoid [a bug in GTK](https://bugzilla.gnome.org/show_bug.cgi?id=85715).

> User cases where it is not preferable to upload her own PKGBUILD to the AUR rather than patching the file each and every time:

Should AUR really be cluttered with packages for every Arch user's preferences? Besides, the maintenance burden of maintaining AUR packages is higher than a local customizepkg setup.

**Comment by rmarquis** [comment]
Current status of customizepkg is that it will never happen. It's ugly, it's incompatible with the RPC dependency solver design, it breaks reliability, and can be replaced with pacman hooks anyway.

**Comment by darkbasic** [comment]
I would like to do the following modifications to an AUR package:
1) Change the git URL
2) Change the git branch
3) Add a new patch to the package
4) Add a new configure option

Is it possible to achieve something like this with pacaur? I mean with pacaur's "basic customizepkg support", with "pacman hooks" or whatever you prefer.

**Comment by rmarquis** [comment]
If you do not mess with dependencies, a pacman hook should work. See [here](https://www.reddit.com/r/archlinux/comments/55p7mw/force_pacman_to_upgrade_some_packages_through/) for an example. This uses ABS but the same principle applies to AUR packages (I guess, I haven't tried).

**Comment by ArchangeGabriel** [comment]
@rmarquis I’m not in favor of cluttering the AUR with each user combination of dependencies/features. I’m already not a great fan of having packages in the AUR for that rather than something based on ABS, but having failed to find anything that would fill this purpose, most of my AUR packages are those kinds of repo alternatives.

I’ve indeed started by making them the way I want (and calling them either -minimal or light). But now I’d like to move them to a more generic and suitable form, like this: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=evince-light

If I understand well, this is not compatible at all with pacaur. That’s too bad considered pacaur is the best AUR helper available out there.

That being said, I understand your RPC point of view. I have no solution at the moment to reconcile both things.

**Comment by rmarquis** [comment]
In fact, there are two scenarios:

* PKGBUILDs that changes dependencies based on some compilation option. This is fundamentally incompatible with the use of the RPC, as using it allows to compute and check dependency the tree consistency it beforehand, ensure correct dependencies order, allows a complete support of split packages, fast computation, etc. I basically gave up on customizepkg support to gain all these advantages, and this is exactly the reason pacaur is one of the most reliable helper.
* PKGBUILDs that changes some compilation option only. As AUR4 uses git to track PKGBUILDs, I guess this could be done internally by using a git branch, and applying some commit/patch on top of the most recent PKGBUILD commit. This can also be done with a pacman hook, so I'm not sure how the complexity could be justified here. Also, I'm not committing time to a feature I don't use, unless someone provides me with a large sum of money. A few people told me they'd work on a patch for this, but I've still yet to see a single line of code - I guess that won't happen soon.

**Comment by ArchangeGabriel** [comment]
Sure, my only interest is the first one indeed. I suppose an hybrid mode (pacaur behaving like it does now unless PKGBUILD was edited) wouldn’t be accepted either?

**Comment by rmarquis** [comment]
No, the core design is fundamentally different. You'd better use yaourt or packer instead.

**Comment by ArchangeGabriel** [comment]
Well, currently there is no AUR helper with “Reliable solver” supporting this apparently (from https://wiki.archlinux.org/index.php/AUR_helpers#Comparison_table). And at least for now, that’s something I need. So I’ll end up using both helpers, which is far from ideal. But I won’t bother you anymore with that, I understand your point and this is your helper, I’ll rather try to get yaourt to be a better AUR helper, and maybe even have them to move toward an hybrid mode. ;)

Anyway, thanks a lot for developing pacaur, and keep up this great work! :)

**Comment by CyberShadow** [comment]
I recall from the IRC channel that some people solved this problem by setting up a personal Pacman repository (which also allows reusing binary packages across multiple machines). That might be a possible solution, though I haven't tried this yet.

**Comment by ArchangeGabriel** [comment]
@CyberShadow I don’t understand how that would solve anything here. Could add links or more details?

**Comment by rmarquis** [comment]
Yes, I'd have a look at aurutils for your need. It's quite modular, and while not as straightforward to as pacaur you might achieve what you need with very minimal scripting needed.

I wouldn't hope to improve yaourt here. To fix its deepest flaw you'd basically need to throw away the whole core design and rebuild from the ground up. It's simply not easy to have both of the design in a single tool.

**Comment by CyberShadow** [comment]
As far as I understood the setup consists of an automated process which, whenever the official or AUR packages are updated, fetches their PKGBUILD etc., patches in the desired changes (e.g. by keeping the customizations in another git branch, and letting git merge figure out how to merge upstream updates with your changes, or as a simple sed/patch/etc. command), builds it to a .pkg.tar.xz, then publishes it to a repo that you can add in your `pacman.conf`. This solves the dependencies problem because it becomes pacman's job to satisfy them, which occurs after your changes are applied.

**Comment by ArchangeGabriel** [comment]
@CyberShadow Not pacman job, but makepkg. ;) However, I also need the case of AUR dependencies, hence the “Reliable solver” requirement.

@rmarquis Will look at aurutils, thanks!

**Comment by CyberShadow** [comment]
> Not pacman job, but makepkg. ;)

No, it's pacman. Mind the distinction between build-time dependencies and runtime dependencies. makepkg is just a bash script which, when requested, invokes pacman to install missing dependencies (as the runtime dependencies are almost always also required at build time).

**Comment by ArchangeGabriel** [comment]
@CyberShadow OK, fair. :)

**Comment by three-comrades** [comment]
I don't quite understand how you could use a pacman hook to patch a PKGBUILD of an AUR packag. As far as I understand, a pacman hook for a foreign package would only ever get triggered once you or an AUR helper calls it with 'pacman -U <pkgname>' - but at this point, pacaur for example would already have downloaded and built the package and you'd have to patch the build files and rebuild, so effectively building the package twice. 
For an official package a pacman hook works, because pacman itself detects that it can upgrade a package and then triggers the hook.

So, as far as I can tell, using a pacman hook would be less than ideal - or am I missing something obvious here?

I did a quick (& probably less than ideal) hack [here](https://github.com/three-comrades/pacaur/commit/8993db49d335c5992d55dfe6816407d3ec9fdbed) that allows for basic patching. So far, `customizepkg` seems like overkill to me - I just provide *.patch files in a directory named after the package.

**Comment by rmarquis** [comment]
> So, as far as I can tell, using a pacman hook would be less than ideal - or am I missing something obvious here?

Yes, this is correct.

> I did a quick (& probably less than ideal) hack here that allows for basic patching. So far, customizepkg seems like overkill to me - I just provide *.patch files in a directory named after the package.

Good. But please note I'm not interested in adding non-ideal half-backed hack to replace another non ideal method of dealing with that issue, especially when the latter just works without any required additional code.

**Comment by three-comrades** [comment]
> Good. But please note I'm not interested in adding non-ideal half-backed hack to replace another non ideal method of dealing with that issue, especially when the latter just works without any required additional code.

I know, no worries.
