### ISSUE TITLE
Specify a local PKGBUILD as target

### ISSUE THREAD

**Issue by thiagowfx** [rmarquis/pacaur#296]
Hi, since I couldn't find any reference on this in the pacaur man page or in previous issues, I created this one.

Here is my **use case**: today I created a new PKGBUILD to upload to the AUR. This PKGBUILD had several dependencies in the AUR, which in turn had other dependencies in the AUR.

**I wanted a way to quickly install all of those dependencies by using pacaur**, so I could test if the PKGBUILD was working okay. So, I listed all of those dependencies in the PKGBUILD (in the `depends` array).

Now, how could I install them all automatically, using pacaur?

I tried things like

`pacaur -m PKGBUILD`

`pacaur -y PKGBUILD`

`pacaur -dd PKGBUILD` (downloading their PKGBUILDs...)

However, I realized they wouldn't work, because they were actually searching for a package in the AUR called 'PKGBUILD'.

**The final question is: does pacaur support specifying a local PKGBUILD?** I ended up using another aur helper to do this task, but in the future I wanted to handle this use case by using pacaur. 

If this feature currently doesn't exist, would it be a good feature request?

Thanks

**Comment by rmarquis** [comment]
That's something I thought about some time ago (see #166), but finally ditched because pacaur doesn't have the code to parse PKGBUILDs locally anymore, as the dependency tree is entirely solved through the RPC interface.

This user case is also so rare for me that it isn't worth my time implementing/maintaining. Copy/Pasting the dependency array on the command line when the need occurs is more than enough. No need for more complexity in pacaur.

Cower supports this feature (-p), but is actually limited since it doesn't handle split packages fully correctly and doesn't have support for the new arch specific arrays yet. I might however use it directly in the future if those aspect are improved.
