### ISSUE TITLE
WARNING: Skipping dependency checks

### ISSUE THREAD

**Issue by eerie** [rmarquis/pacaur#305]
Every time I upgrade an AUR installed package with:
pacaur -S package
I get this yellow warning message: ==> WARNING: Skipping dependency checks.
Why? Do I have to care about it?
Does it have to do with what is wirtten at the top here in the pink frame? https://wiki.archlinux.org/index.php/Pacaur

**Comment by rmarquis** [comment]
No, you shouldn't worry about this warning.

It does appear because since 4.2.17 the integrity of files is checked for all packages, before starting the build - and before downloading deps (makepkg -od). Once the integrity has been checked for all packages, the process resumes with the dependency installation and build (makepkg -e).
