### ISSUE TITLE
pacaur -Syu skips installing aur packages

### ISSUE THREAD

**Issue by beraboris** [rmarquis/pacaur#312]
When I run `pacaur -Syu`, the aur update doesn't fully build/install the packages.

When I run it, I get the [following output](https://gist.github.com/beraboris/82373e134c6fdc375e36#file-log-txt). (It's in a gist since it's rather long)

For all the packages, it downloads the sources, validates them, extracts them, prepares them and then claims the sources are ready and does the same thing for the other packages. It never actually builds any packages.

**Comment by rmarquis** [comment]
Working as intended. Have a look at the last line, the build doesn't start because the integrity check for
`chromium-pepper-flash` fails. And the integrity fails because of:

```
==> ERROR: Failure while downloading google-chrome-stable-40.0.2214.111-1.x86_64.rpm
    Aborting...
```

You should report this to the chromium-pepper-flash maintainer, and you can upgrade the others packages with `pacaur -Syu --ignore chromium-pepper-flash`.
