### ISSUE TITLE
pacaur emits errors when no xdg config

### ISSUE THREAD

**Issue by caipre** [rmarquis/pacaur#331]
This doesn't seem to be causing any problems, but on my first run `pacaur` included this error:
`/home/nick/code/pacaur/pacaur: line 56: /etc/xdg/pacaur/config: No such file or directory`.

Is this a required file?

If not, it should be as simple as changing line 56 to be:
```bash
[[ -f "$configdir/config" ]] && source "$configdir/config"
```

**Comment by rmarquis** [comment]
This is the default, system wide config file which is installed by default when installed with the PKGBUILD.

It looks like you cloned the repo and execute pacaur from it. Any reason not to install it?

**Comment by caipre** [comment]
Only that I'm still learning arch and haven't used the AUR much. What is the recommended way to install?

**Comment by rmarquis** [comment]
Welcome to Arch then!

You'll need to familiarize yourself with the [manual installation process](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages) with makepkg first. This is important as you might run into issues in your Arch career that require manual intervention. And because it's always better to understand what pacaur is doing rather than using it blindly.

In a nutshell, download the [tarball or cower](https://aur.archlinux.org/packages/cower), extract and run makepkg to compile, install dependencies and install cower system wide. Repeat the process with pacaur's tarball, after which you'll be able to run pacaur from the regular command line to install other AUR packages.

I'd also strongly advise to have a look at pacman and makepkg man page, as well as pacaur man page. Hope you enjoy your Arch journey!

**Comment by caipre** [comment]
@rmarquis : Just went through with this, thanks for the instructions!
