### ISSUE TITLE
Add option to build all AUR dependencies even if installed

### ISSUE THREAD

**Issue by jonhoo** [rmarquis/pacaur#349]
Consider the case where host `A` is building some package `P` for host `B`. `A` already has `P` installed, whereas `B` is a clean Arch install with no AUR packages installed. `P` depends on the AUR package `D`. To build the packages for `B`, `A` might run:
```
A $ pacaur --noconfirm --noedit --rebuild -f -m P
```
Because `A` has `P` installed, it also has `D` installed. `pacaur` will therefore only download and build `P`, and not `D`, meaning the resulting package is not installable on `B`.

The only way to get around this problem currently is to explicitly list *all* AUR dependencies of `P` (i.e. `pacaur -m P D`, which becomes very tedious and error-prone if `P` has many dependencies. It would be very useful to have a flag for `pacaur` to say "always build all AUR dependencies"; perhaps something like `--ignore-installed`?

**Comment by rmarquis** [comment]
This makes sense. Incidentally, this is kinda similar to the previous ticket (#346) I opened a few hours ago, but applied to all packages instead of just ```--devel``` packages.

**Comment by rmarquis** [comment]
Done in 79fea341ac9e58209c2269cef22edace10615c81. You can use this option with the new ```--foreign``` command line flag.

**Comment by jonhoo** [comment]
@rmarquis: Minor grammatical error in the README:

> consider already installed foreign dependencies packages.

should be

> consider already installed foreign dependencies.

Also, `--foreign` presumably also applies to `-d` and `-m`, so saying

> When used with install and update operations

is probably misleading?

I'm also slightly confused by the "consider" part. Will this flag to guarantee that the packages are downloaded/built/installed/updated?

**Comment by rmarquis** [comment]
> Minor grammatical error in the README

Good catch!

> Also, --foreign presumably also applies to -d and -m, so saying ... is probably misleading?

Not really, although I agree the two command sets explanation is kinda misleading. Install operation is ```-S```/```-y``` (pacman equivalent/AUR only command set), update is ```-Su```/```u```. This flag will also work with ```-Sw```/```-m```, so I can probably add "download only". 

But the ```-d``` flag only lookup the PKGBUILD, it doesn't build any package. There is no equivalent of that operation in the "pacman set" (at least not yet, it will once ABS is directly implemented in pacman).

But yeah, the two commands set explanation in the whole documentation isn't quite clear, especially in the ```--help``` display.

> I'm also slightly confused by the "consider" part. Will this flag not guarantee that the packages are downloaded/built/installed/updated?

I use "consider" because the extra AUR dependencies are thrown in the dependency calculation, but there are other parameters to take into account in the build process itself:
* If the dependency is already installed and up-to-date, pacaur won't build it again if the ```--needed``` flag is used.
* If the dependency is already available in the local cache and up-to-date, pacaur won't rebuild it again unless the ```--rebuild``` flag is passed.

In your user case, you should simply avoid using the ```--needed``` flag, and the ```--rebuild``` flag is most of the time useless (you want to rebuild a package for some reason, like [a soname bump in one of its dependency](https://wiki.archlinux.org/index.php/Pacman#Partial_upgrades_are_unsupported)).

**Comment by jonhoo** [comment]
I think having `--foreign` work for `-d` too (as in, download this package even though it is locally installed) would still be useful, if only to make the behavior of the flag clearer. It should certainly be documented that it works with `-m`.

You explanation for using "consider" makes sense. I guess I was just thrown off since "consider" sounds like a pretty weak promise. Maybe a better way to phrase it would be "`--foreign` will ignore any locally installed foreign packages when computing dependencies"?

**Comment by rmarquis** [comment]
Quick man page update done in 01646ac23ce01ca97714067580764f2026f9f546, but a complete overhaul is badly needed to make the whole command sets thing clearer.

The ```-d``` command is different from the other commands, since it only download the PKGBUILDs without building anything. In fact, the whole operation is directly handled by cower, and I have no way to make ```--foreign``` work with it. See also https://github.com/falconindy/cower/issues/101.
However, this might become possible in the near future, depending on how git download is implemented in cower (and if it is implemented - there are [partial patches](https://github.com/kyrias/cower/tree/git) existing, but these are still work in progress).

The word "consider" is also used in the explanation of ```--devel```, but I am not sure why you believe it sounds as a weak promise. To me, this sounds more as "take into consideration" or "take into account". I also don't think using "ignore" is better, since it is simply wrong and more misleading imho. The ```--foreign``` flag doesn't ignore anything but it adds dependencies to the calculation and the user eventually ends up with more package built. I am not against a better description, but at this time I don't have any other.

Also, thanks a lot for your feedback! I greatly appreciate it.

**Comment by jonhoo** [comment]
Re 01646ac23ce01ca97714067580764f2026f9f546, shouldn't it say "build", not just "download only" then?

I think of it as a weak promise because when it says it will "consider" installed foreign dependencies, I think of that as what pacaur was doing *before* this patch. It considers them, and then decides *not* to build them because they're already installed. The change is that it will now *ignore* the fact that those packages are installed when deciding what dependencies to build and install.

Happy to help! :)

**Comment by rmarquis** [comment]
> shouldn't it say "build", not just "download only" then?

You hit the nail on the head perfectly here, and that's why the whole doc is somewhat confusing. Since pacaur extends pacman operation, it makes sense to use this description, but extended to the AUR.
For example, the ```-Sw``` operation in pacman is _download only_, which basically translate to _download PKGBUILD, build, but do not install on system_ for AUR packages (```-m``` or ```-Swa```). The fact that pacaur provides a _download PKGBUILD_ operation(```-d```) makes things even more confusing.

In a nutshell, the software has two command sets, and the doc has two different set of description which results in a complete mess.

> I think of it as a weak promise because when it says it will "consider" installed foreign dependencies, I think of that as what pacaur was doing before this patch. It considers them, and then decides not to build them because they're already installed. The change is that it will now ignore the fact that those packages are installed when deciding what dependencies to build and install.

Yes, I see where you getting at here. However, I believe it is better to describe the action according to the end result (ie, more packages being built) rather than at an internal level that is completely hidden to the user.

**Comment by jonhoo** [comment]
> For example, the `-Sw` operation in pacman is download only, which basically translate to download PKGBUILD, build, but do not install on system for AUR packages (`-m` or `-Swa`). The fact that pacaur provides a download PKGBUILD operation(`-d`) makes things even more confusing.

Ah, I see; for pacman, download means download the *package*, not the package *source*, whereas for AUR packages, that would mean download (the source) + build. I still think my change is correct though --- when talking about AUR packages (which is where `--foreign` applies), both "build" *and* "download" are affected, so saying "download only" is not really accurate. Besides, you never use pacman's "download only" terminology anywhere else in the pacaur man pages as far as I can tell?

> However, I believe it is better to describe the action according to the end result (ie, more packages being built) rather than at an internal level that is completely hidden to the user.

Hmm, I'm not sure I agree that it's at an internal level, but it's not that important. If you think consider conveys the meaning the best, then go with that.

**Comment by rmarquis** [comment]
Man page update done in 0e5466e764dee46ca68dae372049e0bbd24c336f, hopefully making it less confusing.

Also, the ```--help``` menu has been slightly improved. It isn't as complete as the man page, and I do not wish to list each and every available option to keep it short and to the point. I'll probably need to add a "also have a look at the man page" statement somewhere.

**Comment by jonhoo** [comment]
They both read better now :+1:

**Comment by jonhoo** [comment]
Just tried actually using this, and it doesn't seem to work as it's supposed to. Building with `--foreign` will not discover uninstalled AUR dependencies at all, causing the build/install to fail!

```
$ pacaur --rebuild -f -m cloud-utils-bzr
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (2): cloud-utils-bzr-latest  euca2ools-3.2.0-1  
Repo Packages (1): python2-yaml-3.11-2  

Repo Download Size:   0.00 MiB
Repo Installed Size:  0.59 MiB

:: Proceed with download? [Y/n] ^C
```
```
$ pacaur --foreign -m cloud-utils-bzr
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (1): cloud-utils-bzr-latest  

:: Proceed with download? [Y/n] 

:: Retrieving package(s)...
:: View cloud-utils-bzr PKGBUILD? [Y/n] 

:: cloud-utils-bzr PKGBUILD viewed
:: Checking cloud-utils-bzr integrity...
==> Making package: cloud-utils-bzr 0.27.r269-1 (Tue Aug 25 08:10:48 EDT 2015)
==> Retrieving sources...
  -> Pulling http://bazaar.launchpad.net/~cloud-utils-dev/cloud-utils/trunk ...
http://bazaar.launchpad.net/~cloud-utils-dev/cloud-utils/trunk is permanently redirected to http://bazaar.launchpad.net/~cloud-utils-dev/cloud-utils/trunk/changes
No revisions or tags to pull.                                                                                                                                                                      
==> Validating source files with md5sums...
    cloud-utils-bzr ... Skipped
:: Building cloud-utils-bzr package(s)...
==> Making package: cloud-utils-bzr 0.27.r270-1 (Tue Aug 25 08:10:53 EDT 2015)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: euca2ools
==> ERROR: 'pacman' failed to install missing dependencies.
==> WARNING: Failed to remove installed dependencies.
:: cloud-utils-bzr cleaning skipped
:: failed to build cloud-utils-bzr package(s)
```

**Comment by rmarquis** [comment]
The ```--foreign``` option only makes sense if you're actually reinstalling packages. Did I miss something here?

**Comment by jonhoo** [comment]
Yes, but it shouldn't *prevent* packages from being built if they *aren't* installed. The idea was that I can tag on `--foreign`, and packages that are installed locally will be built anyway. It should not change the behavior for for packages that aren't installed locally.

**Comment by rmarquis** [comment]
I see - will have a look shortly. Thanks for your feedback!

**Comment by rmarquis** [comment]
Should be fixed in 752ad8c93814699f290d0cf04b8926e8f2878238.

**Comment by jonhoo** [comment]
752ad8c93814699f290d0cf04b8926e8f2878238 seems to be working perfectly. Thanks!

**Comment by rmarquis** [comment]
The --foreign flag might be renamed ==recursive, if that makes sense (see #49).

**Comment by jonhoo** [comment]
Mmm, that would also be fine.

**Comment by rmarquis** [comment]
The ```-S --recursive``` flag has actually been removed in pacman 4.0.3, because it was "poorly implemented" and somewhat related to the deprecated ```SyncFirst``` option. No need to rename the ```--foreign``` flag, it won't be more explicit that way.
