### ISSUE TITLE
Segmentation fault with 'pacaur -Ss aws cli'

### ISSUE THREAD

**Issue by ainola** [rmarquis/pacaur#356]
Running 'pacaur -Ss aws cli' results in:

> /usr/bin/pacaur: line 941:  1322 Segmentation fault      (core dumped) cower ${coweropts[@]} $@

searching with 'pacaur -Ss aws-cli' works properly.

I'm on version 4.2.27-1

**Comment by rmarquis** [comment]
This is a cower issue, and as far as I know it has already been reported there. The corresponding patch has been sent to the maintainer, and this will be fixed shortly. See  https://github.com/falconindy/cower/issues/118 and https://github.com/goreliu/package-query/commit/1e0e2d87f96c1f6ff5f55b0834c6d9cc95c227ce since the very same patch applies to package-query.
