### ISSUE TITLE
Package downloads and builds, but does not install

### ISSUE THREAD

**Issue by veluria** [rmarquis/pacaur#383]
I have seen this issue various times since the 4.4 release, but I don't know why it happens. Certain AUR packages download and build just fine, but they aren't installed afterwards. For example:

    % pacaur -S chromium-snapshot-bin
    :: Package(s) chromium-snapshot-bin not found in repositories, trying AUR...
    :: resolving dependencies...
    :: looking for inter-conflicts...

    AUR Packages  (1):

    Name                       Old Version            New Version          

    aur/chromium-snapshot-bin                         48.0.2535.0.r353757-1               

    :: Proceed with installation? [Y/n] y
    :: Retrieving package(s)...
    Already up-to-date.
    :: View chromium-snapshot-bin PKGBUILD? [Y/n] n
    :: View chromium-snapshot-bin.install script? [Y/n] n
    :: Checking chromium-snapshot-bin integrity...
    ==> Making package: chromium-snapshot-bin 48.0.2535.0.r353757-1 (So 15. Nov 14:19:27 CET 2015)
    ==> Retrieving sources...
      -> Found chromium-snapshot-bin
      -> Found chromium-snapshot-bin.desktop
      -> Found LICENSE
      -> Found chrome-linux-r359769.zip
    ==> Validating source files with md5sums...
        chromium-snapshot-bin ... Passed
        chromium-snapshot-bin.desktop ... Passed
        LICENSE ... Passed
    ==> Validating source files with md5sums...
        chrome-linux-r359769.zip ... Skipped
    :: Building chromium-snapshot-bin package(s)...
    ==> Making package: chromium-snapshot-bin 49.0.2565.0.r359769-1 (So 15. Nov 14:19:28 CET 2015)
    ==> Checking runtime dependencies...
    ==> Checking buildtime dependencies...
    ==> Retrieving sources...
      -> Found chromium-snapshot-bin
      -> Found chromium-snapshot-bin.desktop
      -> Found LICENSE
      -> Found chrome-linux-r359769.zip
    ==> Validating source files with md5sums...
        chromium-snapshot-bin ... Passed
        chromium-snapshot-bin.desktop ... Passed
        LICENSE ... Passed
    ==> Validating source files with md5sums...
        chrome-linux-r359769.zip ... Skipped
    ==> Extracting sources...
      -> Extracting chrome-linux-r359769.zip with bsdtar
    ==> Starting pkgver()...
    ==> Entering fakeroot environment...
    ==> Starting package()...
      -> Creating directory structure...
      -> Making it nice...
      -> Moving contents...
      -> Installing main directory...
    ==> Tidying install...
      -> Purging unwanted files...
      -> Removing libtool files...
      -> Removing static library files...
      -> Compressing man and info pages...
      -> Stripping unneeded symbols from binaries and libraries...
    strip: ./opt/chromium-snapshot/st9u44D5: section .note.gnu.build-id lma 0x3ef60190 adjusted to 0x3f210190
    strip: ./opt/chromium-snapshot/st9u44D5: section .rodata lma 0x3ef601c0 adjusted to 0x3f2101b4
    strip: ./opt/chromium-snapshot/st9u44D5: section .gcc_except_table lma 0x3ef97730 adjusted to 0x3f247724
    strip: ./opt/chromium-snapshot/st9u44D5: section `.gcc_except_table' can't be allocated in segment 1
    LOAD: .note.gnu.build-id .rodata .gcc_except_table
    ==> Creating package "chromium-snapshot-bin"...
      -> Generating .PKGINFO file...
      -> Adding install file...
      -> Generating .MTREE file...
      -> Compressing package...
    ==> Leaving fakeroot environment.
    ==> Finished making: chromium-snapshot-bin 49.0.2565.0.r359769-1 (So 15. Nov 14:19:32 CET 2015)
    ==> Cleaning up...
    :: Installing chromium-snapshot-bin package(s)...

And that's it. Maybe it's because of the different version number?

**Comment by rmarquis** [comment]
I can reproduce. However, this doesn't seem to be a pacaur bug:

On my machine, version ```48.0.2535.0.r353757-1``` should be installed but ```chromium-snapshot-bin-49.0.2565.0.r359778-1-x86_64.pkg.tar.gz``` is created. The version given by the [RPC interface](https://aur.archlinux.org/rpc.php?type=multiinfo&arg=chromium-snapshot-bin&v=4) is ```48.0.2535.0.r353757-1```, so there is definitely something wrong with the SRCINFO file of that package.

Please report upstream.

**Comment by rmarquis** [comment]
Reopening. It seems this package is much like a VCS package that is constantly updated with the very same PKGBUILD. Pacaur does not, however, have support for this name pattern.

**Comment by rmarquis** [comment]
I've got a closer look at this issue, and I'm afraid I won't fix it. Or rather, I cannot fix it in a way that make sense.

This is package that has been uploaded once in the AUR but which content is constantly updated, much like the VCS packages (-git, -svn, -hg, ..). This means pacaur will not detect any new update unless the ```pkgver``` is manually updated by the maintainer.

Since this doesn't happen in practice, pacaur implements the ```--devel``` flag that actually looks at the package names and updates them if it ends with any of the ```-git, -svn, -hg, -bzr, -darcs``` extension. Other helpers such as yaourt and packer do the same too.

Pacaur also supports ```-nightly``` as an additional extension, but there is no defined standard for this and thus the support is [partial only](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=nightly). I could add the ```-snapshot``` extension too, but this would also be [partial only](https://aur.archlinux.org/packages/?O=0&SeB=n&K=snapshot). I won't implement detection of this string anywhere inside the name, as this will result in false positive (see ```snapshot-hib``` or ```zfs-auto-snapshot-git``` for example). Some other package would also be detected as false positive anyway (ie, ```aj-snapshot``` which is the actual name of the project).

I'd suggest you to bring this issue upstream on the AUR mailing list. Without defined naming standard for snapshots or nightly packages, helpers automation support for these packages will always been broken or partially working only at best. Ideally, we could define a new single extension reserved for both *-snapshot and *-nightly packages that could be enforced to existing packages.

Lastly, note that pacaur relies exclusively on the RPC interface (instead of parsing PKGBUILDs) so  some other helpers might be able to install your package properly. Keeping it updated without reinstalling it explictly is however not possible.

**Comment by veluria** [comment]
Okay, thanks for looking into this. Since I rarely use these packages, it's not really important to me and I'll be fine just installing them manually. If you want to discuss this upstream, feel free to do so. I'll be closing this, then.

**Comment by marmistrz** [comment]
I still don't understand why the package doesn't install. What does it have in common with the manual version number? In my case I'm trying to install `atom-editor` (for the first time).

**Comment by rmarquis** [comment]
@marmistrz That issue might happen because of a combining of factors. If you understand the manual process with makepkg, and take into account that the drop of `--pkg` for split packages, you should understand why the install step is more fragile since pacman 5.0.

Since `atom-editor` isn't a VCS package this ticket likely doesn't apply. Please open a new ticket with your debug output.

**Comment by Det87** [comment]
I'm the maintainer of chromium-snapshot-bin. Wouldn't it be possible to just check for the existence of pkgver()?

Does Pacaur really even need to care as much as to abort the build?

**Comment by rmarquis** [comment]
Pacaur and other "modern" helpers rely on the RPC for retrieving the necessary information. The RPC info is wrong, so pacaur fails.

**Comment by rmarquis** [comment]
@Det87: Note that pacaur also treats `-nightly` packages as regular VCS packages. There are more false positive than actual true positive when doing the same with `-snapshot`, so this isn't done. A solution for you could be to rename to `chromium-bin-nightly`, but this is a very pacaur centric solution.

And for clarity: pacaur doesn't parse PKGBUILD, as it relies on the RPC by design. VCS packages are detected solely based on the package name (`-git`, `-svn`, ..), and VCS packages that don't use the extension in the name (such as `packer`) also fail here.

**Comment by Det87** [comment]
Yeah, but "snapshots" is what Google calls them, so I'd rather go with the upstream naming (previously "chromium-browser-bin").

But doesn't this mean you can't e.g. add a new dependency or bump the pkgver with Pacaur? Why couldn't it just print a WARNING?

**Comment by rmarquis** [comment]
Sure, this was only a suggestion - I'd go with the upstream naming scheme too.
I'm afraid I do not understand your questions. Could you elaborate here?

**Comment by Det87** [comment]
I mean, if Pacaur aborts the build every time .SRCINFO and PKGBUILD are not in sync, doesn't it mean when you `pacaur -S pkg` you can't then edit the PKGBUILD when asked to e.g. add a new dependency or bump the pkgver, because Pacaur won't allow differences in the two files?

And then why not just print a warning at the end of the build, instead of aborting the thing.

**Comment by ArchangeGabriel** [comment]
@Det87 Pacaur doesn’t support editing PKGBUILD.

**Comment by rmarquis** [comment]
This is correct. Or rather, pacaur supports limited editing: changing the info provided by the RPC won't work, such as adding new dependencies or changing version number. For tinkering, users should use makepkg manually.

There is a warning when the install fails due to mismatching .SRCINFO data:
> :: chromium-snapshot-bin package(s) failed to install. Check .SRCINFO for mismatching data with PKGBUILD.

**Comment by Det87** [comment]
Yeah, but:
- warning = message
- error = message + abort

But if this is the fundamental approach, I guess that explains all. Thanks for the time.

**Comment by rmarquis** [comment]
Oh, missed that part sorry. Obviously, pacaur does not try to continue in case the package is needed for the next package to build. This doesn't apply to your package, but this is globally a saner approach.
