### ISSUE TITLE
Preserving changes to PKGBUILD

### ISSUE THREAD

**Issue by ggVGc** [rmarquis/pacaur#384]
What is the imagined workflow for when I've got a modified PKGBUILD that I'd like to not have overwritten?
Example scenario:
* Install package with `pacaur -y`
* Modify PKGBUILD during installation for customization of build.
* Something goes wrong during installation, and I'd like to try again.
* ??? How do I now attempt a new install without having to redo my customizations?

Another related scenario is when updating a source package, and the PKGBUILD has only changed slightly. In this instance it's also preferable to not lose customizations, although this would involve merging PKGBUILD's which might be outside the scope of pacaur.

**Comment by rmarquis** [comment]
That would be a feature I consider as out of scope of this automated helper. One of the reason is that pacaur relies on the info provided by the AUR RPC interface, and PKGBUILDs are not sourced for dependencies. The other reason is that I won't work on features that I don't use myself, nor do I want to maintain them.
 
For customization, use cower and the manual way. Alternatively, use a helper that supports customizepkg.
