### ISSUE TITLE
Pacaur doesn't seem to respect IgnoreGroups for non-repo packages

### ISSUE THREAD

**Issue by zoqaeski** [rmarquis/pacaur#388]
I occasionally modify AUR packages (especially devel ones) to point to my local copies of the sources. When I run `pacaur <OPERATION> --devel` it searches the AUR for those packages and overrides my local versions, despite me having added `groups=('local-builds')` to each and `IgnoreGroups=local-builds` to `/etc/pacman.conf`.

**Comment by rmarquis** [comment]
That's because AUR packages don't have groups. I am not even sure the RPC info would return such information. I can add a check for it, sounds good.

**Comment by zoqaeski** [comment]
I just checked a few queries on the RPC info, and it doesn't return the groups, so I'm not sure how this could be implemented short of reading cached PKGBUILDs. But even if you did that, any PKGBUILDs that were modified by the user will be overwritten on the next upgrade anyway, [due to the `git pull --hard HEAD` in `DownloadPkgs()`](https://github.com/rmarquis/pacaur/blob/master/pacaur#L692). Either way, it'll probably be a difficult problem to solve. By my naïve reckoning, at a minimum pacaur would have to:
* get a list of all foreign packages; and
* check the clonedir to see if they've already been downloaded;
 * if so, read the PKGBUILDs without sourcing them (!) to find the groups and compare that against the `IgnoreGroups` in `/etc/pacman.conf`; 

before proceeding as normal. There's probably a few more steps along the way in the rest of the build process that I've missed.

For the time being, I've just added a workaround to my local builds so the packages are called `${pkgname}-local` and they conflict, provide and replace the original package. After all, I'm using my own forks of the sources so I'm keeping up-to-date elsewhere.

**Comment by rmarquis** [comment]
> if so, read the PKGBUILDs without sourcing them (!)

This is the reason pacaur avoids to do it and use the RPC interface instead. It is insecure to parse the whole PKGBUILD directly, and parsing PKGBUILD without parsing them is difficult and inaccurate when dealing with complex PKGBUILDs. Please forward your request to the AUR-dev mailing list for implementing groups in the RPC interface.

This said, pacaur has never been intended to manage packages modified by the user - it just doesn't make sense. Rather, you should use cower instead of an automated helper (luckily cower is already installed if you are using pacaur). I'm not against implementing little features if they require only minimal work and maintenance, but in this case it's much work for something I don't use myself, and in which I don't want to invest time. Patches welcome. In the meantime, I'll just close this ticket.
