### ISSUE TITLE
Update: no results found for 'error'

### ISSUE THREAD

**Issue by 5chdn** [rmarquis/pacaur#412]
pacaur -Syua : no results found for 'error'

See logs: https://gist.github.com/5chdn/0142ded4743117c2d06a

Using pacaur 4.4.5
Archlinux kernel 4.3.3-3-ARCH x86_64 GNU/Linux

**Comment by rmarquis** [comment]
Please update to pacman 5.0, expac 5 and recompile cower. And also install the latest pacaur 4.5.0. Does the issue still happen?

**Comment by 5chdn** [comment]
Reinstalling pacman, expac and cower did the trick. They were already at latest version though.

**Comment by rmarquis** [comment]
Cower needs to be recompiled when the libalpm got a soname bump, which happens when a new major pacman version is released.

Note this is also valid for any AUR package (C, C++, ..) that depends on another library API. If the dependency is updated, the package needs to be recompiled manually. No tool will do that for you.

**Comment by 5chdn** [comment]
Thanks again for your help :+1:
