### ISSUE TITLE
Delete files in pacaur-tmp when installing again without reboot

### ISSUE THREAD

**Issue by brittyazel** [rmarquis/pacaur#420]
I noticed today an issue when installing an update to Terminix just a few hours after initially installing Terminix. Since the update happened is close temporal proximity to the initial install, the build files were still in pacaur-tmp, and Terminix reported that the validity check failed. I was forced to delete the previous terminix build files out of tmp before the update would install.

Is there a way we can check if a folder already exists for that package, and delete it before installing a package? I don't reboot my laptop often, and it is annoying to have to purge out files from /tmp manually just to install an update without it failing

**Comment by rmarquis** [comment]
It seems terminix is a pre-compiled binary with a unique filename, regardless of the version. As stated in the terminix AUR comments, the package should be renamed to `terminix-bin`.

This said, I am not sure how to fix that issue without forcing redownload for all packages, which would be silly. This likely also happens when `SRCDEST` is enabled, which is even worst. I'll have a closer look, but my first recommendation would be to fix the issue upstream, either by using a naming scheme that includes the version, or by using an alternative PKGBUILD that compiles the package from source.

**Comment by rmarquis** [comment]
Yep, can't be fixed easily. Since naming release/binary release with the very same name is very unconventional and not very practical either, I'd consider this an upstream issue to be reported to the package/project maintainer. Closing as 'Wontfix'.

**Comment by brittyazel** [comment]
I reported upstream

**Comment by rmarquis** [comment]
Good. Also, as a cheap workaround you might be able to use `-Sca` to remove downloaded source files, if you set up `$SRCDEST` first. See makepkg.conf manual.
