### ISSUE TITLE
Allow sort in ascending or descending order

### ISSUE THREAD

**Issue by simonbcn** [rmarquis/pacaur#439]
I have defined sort by votes. When I search in AUR the last results I see in console are the least votes, with a reverse order the last results showed would be the most votes.

**Comment by rmarquis** [comment]
A `--sort` and `--rsort` options need to be added. At the moment, `--rsort` is passed to cower by default.

Also, the sort command line options (--asort, --psort, --vsort) also need to be reworked. Having two options only somewhat made sense, but since AUR 4 `--psort` has been added. This is hardly a clean implementation. They should be replaced by `--[r]sort=(alpha|votes|popularity)` with default set in the config file.

**Comment by rmarquis** [comment]
Done in 3a5b7a9340ae43e04c6cadeee0b21d314cde1530.
