### ISSUE TITLE
--repo flag

### ISSUE THREAD

**Issue by AladW** [rmarquis/pacaur#463]
9fcf252e019f89d3fb62c6b90f1a4566b2dd433b and c9b3aa232deac58c7063b4ec414633dd57534c4d removed support for `--ignorerepo`, and with that, checking of updates in (local) repositories. Before that, you could do something like:
```
pacaur --ignorepo=custom -Syu # PKGDEST=/home/packages
repose -vf custom.db -p /home/packages -r /home/packages
```
However the inverse `--ignorerepo` logic isn't optimal anyway (and fails for me in some cases), so I'd like to prepose a `--repo` flag.

This flag would add the packages in `pacman -Slq <repo>` to the `GetJson` queries, for example by adding them to the existing `foreignpkgs` array:
```
foreignpkgs=($("$pacmanbin" -Qmq) $("$pacmanbin" -Slq "${repolist[@]}"))
```
Where `repolist` would be built from getopts.

edit: You'd have to add some logic to return empty when the repolist array is empty, e.g. `printf '%s\n' "${repolist[@]}" | xargs -r ...`

**Comment by rmarquis** [comment]
Do you mind explaining how the ``--ignorerepo`` logic fails in some cases? And if I understand correctly, the sole purpose of this feature would be to add some compatibility layer with aurutils, is this correct?

Also, I don't have for habit to implement feature requests that I personally have no use for, and packages that are both in the repo and the AUR with a different version are already supported by pacaur, I am not sure if that actually makes sense to add it.

So I am wondering, would it make more sense to implement this in a separate little wrapper, that you could use with any helper that do not use a local repository (basically all existing helpers apart from aurutils)?

Note I went away from the cower ``--ignorerepo`` flag since not using cower for update process avoids when the libalpm bumps, which also means less idiotic bug reports for me. It's also slightly faster as a bonus. And I did add ``--ignorerepo`` since it was a single easy line of code, but I wouldn't mind just get rid of this capability.

Lastly, note also that the ``--repo`` flag is already taken by another option.

**Comment by AladW** [comment]
I more suggest it because I use repose, and generally others who do so, 
not particularly related to aurutils. As to cower, I'm not sure on the 
internals of the --ignorerepo command, but it sometimes misses packages. 
I'll add some detail on that if I find out more.

Either way, I hadn't considered that pacaur would handle new AUR 
versions transparently. I'm not sure on how to write a wrapper like you 
suggest though, unless by fooling helpers in somehow using a different 
pacman config. :)

About replacing cower for updates, I figured you had a good reason for 
changing it, so I don't object that.

About the name, something like `--addrepo` could do, but that can always 
be decided if you do (or don't) wish to implement this option.

**Comment by AladW** [comment]
I've tried `pacaur -Syu` to update `albert` from 0.8.7.1-1 to 0.8.7.2-1 (in a file:// repository), but the output was `there is nothing to do`. 

About the wrapper, I forgot you can simply use the `PACMAN` variable, which could refer to something like:
```
#!/bin/bash
tmp=$(mktemp -d)
printf '%s\n%s\n' '[core]' "$(pacconf --repo=core)" >> "$tmp"/config
printf '%s\n%s\n' '[extra]' "$(pacconf --repo=extra)" >> "$tmp"/config
printf '%s\n%s\n' '[community]' "$(pacconf --repo=community)" >> "$tmp"/config

pacman --config="$tmp"/config "$@"
```
(This only works with installed packages, but that's expected)

So I think you're right in taking this route, thanks. If you want me to open a new issue on different repo/AUR versions thing, let me know.

**Comment by rmarquis** [comment]
Great, using `$PACMAN` env var sounds like the perfect solution here.

I am not sure what happens with that file repository, I would have thing pacman would handle the update himself. Please do open an issue, although I am not sure if that issue is relevant in the pacaur context.
