### ISSUE TITLE
pacaur does not honor IgnorePkg in cower's config

### ISSUE THREAD

**Issue by junag** [rmarquis/pacaur#493]
according to the man page "Packages listed in pacman and cower's IgnorePkg directive are honored." However I have `IgnorePkg = ttf-win7-fonts` in my `$HOME/.config/cower/config` (and indeed `cower -u` reports `warning: ttf-win7-fonts [ignored] 7.1-8 -> 7.1-9`), but `pacaur -k` says `:: aur  ttf-win7-fonts  7.1-8  ->  7.1-9`. This happens with `pacaur 4.6.3-1` and with `pacaur-git-4.6.3.1.g4d36c53-1`

**Comment by rmarquis** [comment]
Cower isn't used anymore for update check since 4.6.0, and support for cower's IgnorePkg directive has been removed altogether too (see c9b3aa232deac58c7063b4ec414633dd57534c4d). It is however still possible to honor this parameter - and this might actually be a better idea than completely ignoring it. I'll readd it.

**Comment by rmarquis** [comment]
Done in 84941ecc1dc81c5e3788a7804bfcc3e2de9c0f5f.
