### ISSUE TITLE
"Value too great for base" when upgrading AUR packages

### ISSUE THREAD

**Issue by saghm** [rmarquis/pacaur#505]
When trying to upgrade my packages (via `pacaur Syu`), I get the following output:

```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Starting AUR upgrade...
:: resolving dependencies...
:: looking for inter-conflicts...
/usr/bin/pacaur: line 707: sumk + 0936: value too great for base (error token is "0936")
```

I haven't booted this system for at least a week or so, so I imagine there could be a fairly large number of AUR packages that need to be upgraded, but I've never had any issue when trying to upgrade my AUR packages after longer periods of time than that, so I'm not sure if there could be any issue related to that.

The output of `bash -x pacaur -Syu` is [here](http://pastebin.com/Mff5xJtm). It's quite long, so I apologize in advance if this isn't usually the case.

Any suggestions about what I can do to fix this? I'm hoping that it's just something on my end, although I don't recall having changed anything since the last time I upgraded my AUR packages.

**Comment by rmarquis** [comment]
The error happens when adding repo packages size, to display the total download or install size on the main prompt. It seems very small values keep the initial '0', and as such '08..' and '09..' are computed as octal values. Which of course are non existing numbers in base 8.

I don't know why this happens on your system. Do you see any value that start with 0 with the following command: `expac -S '%k\t\t%n`? If yes, what is the name of the package on the corresponding package?

**Comment by rmarquis** [comment]
No response, closing as 'invalid'. I assume the issue is on your side.
