### ISSUE TITLE
pacaur fails to install/update jabref

### ISSUE THREAD

**Issue by nplatis** [rmarquis/pacaur#529]
The error message is 
```
==> Extracting sources...
  -> Extracting JabRef-3.5.jar with bsdtar
com/: Can't replace existing directory with non-directory
```
and then too many lines with the same error.

`yaourt` is able to install/update `jabref` fine.

I don't know if it is a problem with `pacaur` or the package, but I thought I should report it.

**Comment by ixjlyons** [comment]
This could be fixed by the package maintainer -- they could put the jar file in `noextract` and extract it in `prepare()` for example ([reference](https://bugs.archlinux.org/task/11909)).

But the problem seems to be that [this line](https://github.com/rmarquis/pacaur/blob/41a308276221e1d397383f735491de41dd5a647b/pacaur#L942) extracts the contents of the jar to src, then the subsequent `makepkg` call to actually build the package tries again to extract the contents, causing the errors. Does it make sense to throw in a `--noextract` [here](https://github.com/rmarquis/pacaur/blob/41a308276221e1d397383f735491de41dd5a647b/pacaur#L1030)? I'm not all that familiar with the `pacaur` code, so apologies if that's a stupid suggestion.

**Comment by nplatis** [comment]
According to your reference it seems it was a problem with the package, not with `pacaur`, and, most importantly, it has already been solved after some (seemingly independent!) comments in https://aur.archlinux.org/packages/jabref/

Closing this issue, if someone feels that something relevant should be done in `pacaur` please re-open.

**Comment by rmarquis** [comment]
This was a pkgbuild issue.
