### ISSUE TITLE
PKGBUILD editing before install dependencies 

### ISSUE THREAD

**Issue by music-fan** [rmarquis/pacaur#620]
In some PKGBUILD, the dependencies should be edited, before installing them. (for example: 'gtkhash' packages - if I don't want a cinnamon desktop, I should edit the PKGBUILD before installing the dependencies).

**Comment by rmarquis** [comment]
See #614.

**Comment by ArchangeGabriel** [comment]
@rmarquis This isn’t really the same use case as #614.

Do you mean that the PKGBUILD should only have minimal dependencies listed and tell people to edit it to add what is needed? Would that even work with pacaur since dependencies are installed before PKGBUILD editing? Or are there also installed after that phase, in which case I have to ask what purpose serves the first install part?

Or do you advocate for one AUR package for each set of possible dependencies for a given package?

**Comment by rmarquis** [comment]
True, but the underlying issue is the same. See #12 for my opinion of customizepkg and similar. Modifying PKGBUILDs on the fly has many disadvantages, and none outweigh the benefits to use the RPC.

If you need temporary tinkering, do it manually and work with the maintainer upstream. If you want permanent changes, maintain your own PKGBUILDs in the AUR, or use a pacman hook (might or might not apply here).

**Comment by ArchangeGabriel** [comment]
OK, I’ll continue on #12 then. ;)
