### ISSUE TITLE
Unknown dependency conflict

### ISSUE THREAD

**Issue by onny** [rmarquis/pacaur#629]
###### Version

`pacaur -v`

```
4.6.10
```

###### Description

Running pacaur -Su I get following message:
```
onny@onnuex ~ % pacaur -Sy
:: Synchronizing package databases...
 testing is up to date
 core is up to date
 extra is up to date
 community-testing is up to date
 community is up to date
 multilib-testing is up to date
 multilib is up to date
onny@onnuex ~ % pacaur -Su
:: Starting full system upgrade...
 there is nothing to do
:: Starting AUR upgrade...
:: resolving dependencies...
:: no results found for perl<
```
I understand that there's a faulty or incompatible AUR package installed on my system but I cannot say which one. Pacaur should be more verbose here!

###### Debug output

Here's my debug output: https://gitlab.com/snippets/579175

**Comment by rmarquis** [comment]
See #173. The fix for that very issue has been pushed literally 3 hours ago :)

**Comment by rmarquis** [comment]
Reopening. Seeing `perl<`, it's possible there is some versioning issue here. Please test `pacaur-git` and see if the issue is still present.

**Comment by rmarquis** [comment]
Just checked the [AUR metadata](https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=perl-goo-canvas) through the RPC, and that particular issue is due to a [faulty .SRCINFO/PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/.SRCINFO?h=perl-goo-canvas).

You'll have to ask the maintainer to fix that issue. Pacaur should however be more verbose in case a dependency isn't found.
