### ISSUE TITLE
PKGBUILD error: pod2man not found (wayland)

### ISSUE THREAD

**Issue by bulletmark** [rmarquis/pacaur#638]
Version pacaur 4.7.0-1.

I wrote this as a comment on the pacaur AUR web page but thought it best to raise a bug. Since pacaur 4.7 I, and at least one other person on the AUR page, get an error when updating pacaur about `pod2man: command not found`. The reason is because I am using Wayland and it does not source `/etc/profile` so the perl path is not set via `/etc/profile.d/`. See https://bugzilla.gnome.org/show_bug.cgi?id=736660.

An easy fix is just to specify the full path `/usr/bin/core_perl/pod2man` in the PKGBUILD which fixes the issue.

**Comment by rmarquis** [comment]
Hum, interesting. Skimming through the long bug report, I wasn't able to determine if RH/Gnome pushed a temporary workaround in Fedora or if the issue should be somehow fixed by wayland/systemd instead.

In any case, it might be worth raising this issue on the Arch mailing list if this isn't done already. Pod2man is only used for generating the man page from the README.pod, but this issue goes beyond a simple workaround for pacaur only. Cower does generate its man page in the same way, so that workaround would need to be applied there too, otherwise this is pointless. Finding a general patch/workaround for the entire distribution seems to be the correct approach here.

**Comment by bulletmark** [comment]
I raised Arch bug https://bugs.archlinux.org/task/52837 for this.

**Comment by bulletmark** [comment]
Which they already closed, "will not fix".

**Comment by rmarquis** [comment]
Reason for closing is "Upstream" (see [#51341](https://bugs.archlinux.org/task/51341)). Not much to do here.

**Comment by AladW** [comment]
Simple fix: write the README in groff instead of pod ¯\ʔ•ᴥ•ʕ/¯

Not that there's much difference in the syntax anyway, besides some added verbosity for pod. compare:
https://raw.githubusercontent.com/rmarquis/pacaur/master/README.pod
https://raw.githubusercontent.com/AladW/aurutils/master/man7/aurutils.7

**Comment by rmarquis** [comment]
The reason I'm using POD is because I want the man page to be readable online. Can this be done with groff?

**Comment by AladW** [comment]
Typical github preferring bloat like topics and emojis rather than actual useful features such as groff previews:

https://github.com/github/markup/issues/342

However, you can do it the other way around: write the readme in groff, then convert it to some previewable convert with e.g. pandoc. Said conversion could be done in a pre-commit hook or such.

**Comment by rmarquis** [comment]
Doing it on my end isn't worth it for an upstream bug workaround. Also, this depends on cower too, since it is a direct dependency.

I'd heavily consider getting rid of perl if GitHub allows preview of some other format than .pod.

**Comment by bulletmark** [comment]
If anybody else come here looking at this problem then you are probably also running GNOME on Arch which now defaults to using Wayland so the easiest and best fix I have researched is to change the first line of `/usr/bin/gnome-session` from:

    $!/bin/sh

to

    #!/bin/bash -l

As per https://bugzilla.gnome.org/show_bug.cgi?id=736660, this issue is in the pipeline to get fixed properly but that small patch is the best fix (On Arch) in the meantime.
