### ISSUE TITLE
Consider a 'need any version' option, like `--needed`?

### ISSUE THREAD

**Issue by OJFord** [rmarquis/pacaur#713]
Sometimes I want to install a package if it doesn't already exist, but if I have it I'm not bothered about upgrading it.

In this case it would be useful to be able to replace a `-Qs` if-guard with something like `-S --needany`.

Another use-case is faster `--needed` checks (particularly of AUR packages) when it is known that every package on the system is at the latest version. (Or at least, it was at the time of the previous line of a script, for example.)

**Comment by rmarquis** [comment]
1/ It sounds like `--ignore` and `IgnorePkg` is just what you need here.
2/ `--needed` is slow only when used in conjunction with `--devel`, so I'm assuming you're referring to these two flags here. This is actually the reason the check is done after the main prompt and not before, and I don't think speed is really important here, since no user input is required. Also, the workaround is simple: don't use `--needed --devel` at any time, but only when you really need to update devel packages.

**Comment by OJFord** [comment]
Thanks for your reply.

I'm not sure if I understand `--ignore`, is that for ignoring upgrades of dependencies? For example, `pacaur -S --ignore pkg` complains of no targets specified, while `pacaur -S --needed pkg` would say `pkg` is up to date, skipping.

Regarding speed, that was a minor point, but I wasn't using `--devel`, I just noticed it can be much slower for AUR packages due to the download step before checking if up to date. Whereas if all you care about is that *some* version is installed, `-Q` is quicker due to not needing that step.


P.S.
Because I do appreciate all the work you put into pacaur, (and read `man` pages)
![cat picture](https://drscdn.500px.org/photo/103795679/m%3D2048_k%3D1_a%3D1/31b424a07da2143f34fb9cfdd5b6091f)

**Comment by rmarquis** [comment]
> I'm not sure if I understand --ignore, is that for ignoring upgrades of dependencies? 

You can use it to prevent the installation of a package, or prevent the update of an installed package (`pacaur -Su --ignore pkg`). Pacman works exaclty the same way. See also `IgnorePkg` in pacman.conf, since you might not want to use the command flag every time. 

> Regarding speed, that was a minor point, but I wasn't using --devel, I just noticed it can be much slower for AUR packages due to the download step before checking if up to date. Whereas if all you care about is that some version is installed, -Q is quicker due to not needing that step.

Sorry, I didn't formulate correctly but this is what I'm talking about. `-Q` is used for all regular packages, unless the package is a VCS package (git, svn, ..) as there is no way to get the current VCS version without updating the sources.

For regular AUR packages:

```
$ pacaur -S cower --needed
:: Package cower not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...
:: cower-17-2 is up to date -- skipping
 there is nothing to do
```

For VCS AUR packages:

```
$ pacaur -S cower-git --needed
:: Package cower-git not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...
:: cower-git latest revision -- fetching

AUR Packages  (1)  Old Version      New Version

aur/cower-git      17.4.g79c42eb-1  latest

:: Proceed with installation? [Y/n] y
:: Retrieving package(s)...
:: cower-git build files are up-to-date -- skipping
:: Checking cower-git integrity...
==> Making package: cower-git 17-1 (Fri  7 Jul 12:25:25 CEST 2017)
==> Retrieving sources...
  -> Updating cower git repo...
Fetching origin
==> Validating source files with md5sums...
    cower ... Skipped
:: cower-git is up-to-date -- skipping
```

If you have a specific example where this operation is slow and doesn't involve a VCS package, please let me know.

Thanks for the cat picture, I definitely get too few of them :)
