### ISSUE TITLE
Humble petition: I modified and improved linux-drm-tip-git package and has pacaur issues

### ISSUE THREAD

**Issue by timofonic** [rmarquis/pacaur#748]
Hello.

I did a hard work with assistance from some people to improve a package I need because stable Intel graphics drivers are buggy in my system. I also need to so some testing to check if the issues are gone

Here's "my" package, I asked a lot people and had a git crash course. It's far from perfect, I acknowledge
https://aur.archlinux.org/pkgbase/linux-drm-tip-git/

It fails at building in some way, but I managed to install the generated packages from pacaur cache.

 => Finished making: linux-drm-tip-git r693733.5118c7fa9c87-1 (Wed Aug 16 04:06:19 CEST 2017)
 ==> Cleaning up...
 :: Installing linux-drm-tip-git package(s)...
 :: linux-drm-tip-git package(s) failed to install.
 :: ensure package version does not mismatch between .SRCINFO and PKGBUILD
 :: ensure package name has a VCS suffix if this is a devel package

```
linux-drm-tip-git]$ ls
90-linux.hook
drm-tip
linux-drm-tip-git.preset                                 
linux.install config.i686    
linux-drm-tip-git-headers-r693256.2d0288b5b28c-1-x86_64.pkg.tar.xz
linux-drm-tip-git-r693256.2d0288b5b28c-1-x86_64.pkg.tar.xz
linux.install.pkg config.x86_64
linux-drm-tip-git-headers-r693733.5118c7fa9c87-1-x86_64.pkg.tar.xz
linux-drm-tip-git-r693733.5118c7fa9c87-1-x86_64.pkg.tar.xz
PKGBUILD
--

```

I understand you're busy but: What can I do to improve the package and work correctly in pacaur? I'm really sorry, but I'm unable to find someone to assist me at improve the AUR package to get full pacaur compatibility.

Thanks in advance.

**Comment by rmarquis** [comment]
Looks like the version generated is correct, but something is fishy in the name generated of the split packages:

* `linux-drm-tip-git` (OK)
* `linux-drm-tip-git-headers` (instead of `linux-drm-tip-headers-git`)

The `package` array is missing too. See [wiki reference](https://wiki.archlinux.org/index.php/PKGBUILD#pkgname). Try using `package_linux-drm-tip-git()` and `package_linux-drm-tip-headers-git()` instead of using the variable generated by your `_package` hack at the PKGBUILD bottom.

Also, note you can find support in this official forum: [AUR Issues, Discussion & PKGBUILD Requests](https://bbs.archlinux.org/viewforum.php?id=38).
